In [1]:
class Human:
    def __init__(self, name:str, age:int) -> None:
        """A class that takes in name and age of a person

        Args:
            name (str): Name of the person
            age (int): Age of the person
        """
        self.name = name
        self.age = age

    def __str__(self) -> str:
        return f"Your name is {self.name}, and you are {self.age} years old."
    
    def __gt__(self, person):
        return person.age < self.age
    
    def __eq__(self, person):
        return self.age == person.age

In [2]:
person1 = Human("Sam", 22)
print(person1)

Your name is Sam, and you are 22 years old.


In [3]:
person2 = Human("Jane", 30)
print(person2)

Your name is Jane, and you are 30 years old.


In [4]:
person1 > person2

False

In [5]:
person1 == person2

False

IRIS DATASET

In [7]:
import pandas as pd

In [8]:
data = {
    "Sepal_Length": [5.1, 4.9, 4.7, 4.6, 5.0],
    "Sepal_Width": [3.5, 3.0, 3.2, 3.1, 3.6],
    "Petal_Length": [1.4, 1.4, 1.3, 1.5, 1.4],
    "Petal_Width": [0.2] * 5,
    "Species": ["setosa"] * 5
}

df = pd.DataFrame(data)
df

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
df[(df.Sepal_Length > 5) & (df.Sepal_Width > 3)]

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  setosa

NumPy

In [10]:
import numpy as np

In [12]:
arr = np.zeros((5, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
arr1 = np.array(range(1, 4, 1))
arr2 = np.array(range(4, 7, 1))

In [14]:
arr1 + arr2

array([5, 7, 9])

In [17]:
np.sum((arr1, arr2), axis=1)

array([ 6, 15])